### ISSUE TITLE
This repo already exists

### ISSUE THREAD

**Issue by Jntzko** [TAMS-Group/tams_camera_config#1]
We already have a repository for camera calibration files:
https://git.mafiasi.de/TAMS/calibration_files

**Comment by lianghongzhuo** [comment]
Could you add me into this repo? I currently not in it.

**Comment by lianghongzhuo** [comment]
How about merge that package here and make this repo public?
@Jntzko @v4hn @philipp1234

**Comment by lianghongzhuo** [comment]
Yannick thinks it's not make sense to make it public, so for now I'll leave it private.

**Comment by Jntzko** [comment]
It just makes no difference, no one except us can use the config files

**Comment by v4hn** [comment]
This is a clone of the mafiasi repository with an additional configuration, right?

I think it makes a lot of sense to make this a public repository here and deprecate the one on mafiasi.
Mafiasi does not support (entirely) public access.
This is nothing internal, although it's not very useful without access to the hardware.
Still, it can break workspaces if public packages can depend on it.

**Comment by lianghongzhuo** [comment]
Yes, if not everyone has the mafiasi access, it makes sense to let students use this repo also.

**Comment by v4hn** [comment]
Every potential person who gets access to our cameras can also register a mafiasi account.
But they wouldn't *need* it just for a configuration file...

**Comment by lianghongzhuo** [comment]
Yes

**Comment by lianghongzhuo** [comment]
Close due to no more action here.
Feel free to comment here and I can reopen.
